name: milan
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  path_provider: ^1.6.21
  sqflite: ^1.3.1+2
  intl: ^0.16.1
  timeline_list: ^0.0.5
  flutter_dropdown: ^0.0.8
  day_night_time_picker: ^0.3.0+2
  date_picker_timeline: ^1.2.1
  flushbar: ^1.10.4
  focused_menu: ^1.0.1
  modal_bottom_sheet: ^0.2.0+1
  shared_preferences: ^0.5.12
  draggable_fab: ^0.1.1
  table_calendar: ^2.3.0
  after_layout: ^1.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf